// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudMonitoringV3
import GoogleCloudWKT

func sample(
  client: NotificationChannelServiceClient, projectId: String, notificationChannelId: String
) async throws {
  let response = try await client.updateNotificationChannel(
    request: UpdateNotificationChannelRequest()
      .with {
        $0.notificationChannel = NotificationChannel().with {
          $0.name = "projects/\(projectId)/notificationChannels/\(notificationChannelId)"
        }
        $0.updateMask = GoogleCloudWKT.FieldMask(paths: ["field.path1", "field.path2"])
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudMonitoringV3.NotificationChannelServiceClient()
      try await sample(
        client: client, projectId: "[placeholder]", notificationChannelId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
