// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AlertPolicyServiceLogging: AlertPolicyServiceStub {
    let inner: any AlertPolicyServiceStub
    let logger: Logger

    public init(_ inner: any AlertPolicyServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-monitoring-v3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AlertPolicyService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listAlertPolicies(
      request: ListAlertPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAlertPolicies",
        action: {
          (r: ListAlertPoliciesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse
          in
          return try await self.inner.listAlertPolicies(request: r, options: o)
        })
    }

    public func getAlertPolicy(
      request: GetAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAlertPolicy",
        action: {
          (r: GetAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.AlertPolicy
          in
          return try await self.inner.getAlertPolicy(request: r, options: o)
        })
    }

    public func createAlertPolicy(
      request: CreateAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAlertPolicy",
        action: {
          (r: CreateAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.AlertPolicy
          in
          return try await self.inner.createAlertPolicy(request: r, options: o)
        })
    }

    public func deleteAlertPolicy(
      request: DeleteAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAlertPolicy",
        action: {
          (r: DeleteAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAlertPolicy(request: r, options: o)
        })
    }

    public func updateAlertPolicy(
      request: UpdateAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAlertPolicy",
        action: {
          (r: UpdateAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.AlertPolicy
          in
          return try await self.inner.updateAlertPolicy(request: r, options: o)
        })
    }
  }
}
