// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An SLI measuring performance on a well-known service type. Performance will
/// be computed on the basis of pre-defined metrics. The type of the
/// `service_resource` determines the metrics to use and the
/// `service_resource.labels` and `metric_labels` are used to construct a
/// monitoring filter to filter that metric down to just the data relevant to
/// this service.
public struct BasicSli: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// OPTIONAL: The set of RPCs to which this SLI is relevant. Telemetry from
  /// other methods will not be used to calculate performance for this SLI. If
  /// omitted, this SLI applies to all the Service's methods. For service types
  /// that don't support breaking down by method, setting this field will result
  /// in an error.
  public var method: [Swift.String] = []

  /// OPTIONAL: The set of locations to which this SLI is relevant. Telemetry
  /// from other locations will not be used to calculate performance for this
  /// SLI. If omitted, this SLI applies to all locations in which the Service has
  /// activity. For service types that don't support breaking down by location,
  /// setting this field will result in an error.
  public var location: [Swift.String] = []

  /// OPTIONAL: The set of API versions to which this SLI is relevant. Telemetry
  /// from other API versions will not be used to calculate performance for this
  /// SLI. If omitted, this SLI applies to all API versions. For service types
  /// that don't support breaking down by version, setting this field will result
  /// in an error.
  public var version: [Swift.String] = []

  /// This SLI can be evaluated on the basis of availability or latency.
  public var sliCriteria: OneOf_SliCriteria? = nil

  /// Initialize a new instance of `BasicSli`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BasicSli().with { $0.method = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case method = "method"
    case location = "location"
    case version = "version"
    case availability = "availability"
    case latency = "latency"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.method = try container.decode([Swift.String].self, forKey: .method)
    self.location = try container.decode([Swift.String].self, forKey: .location)
    self.version = try container.decode([Swift.String].self, forKey: .version)

    var sliCriteria: OneOf_SliCriteria? = nil
    let sliCriteriaCheckAndSet = {
      if sliCriteria != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sliCriteria'"))
      }
      sliCriteria = $0
    }
    if let availability = try container.decodeIfPresent(
      BasicSli.AvailabilityCriteria?.self, forKey: .availability)
    {
      try sliCriteriaCheckAndSet(.availability(availability))
    }
    if let latency = try container.decodeIfPresent(BasicSli.LatencyCriteria?.self, forKey: .latency)
    {
      try sliCriteriaCheckAndSet(.latency(latency))
    }
    self.sliCriteria = sliCriteria
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.method, forKey: .method)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.version, forKey: .version)

    if let choice = self.sliCriteria {
      switch choice {
      case .availability(let value):
        try container.encode(value, forKey: .availability)
      case .latency(let value):
        try container.encode(value, forKey: .latency)
      }
    }
  }

  /// Future parameters for the availability SLI.
  public struct AvailabilityCriteria: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `AvailabilityCriteria`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AvailabilityCriteria().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.BasicSli.AvailabilityCriteria"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters for a latency threshold SLI.
  public struct LatencyCriteria: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Good service is defined to be the count of requests made to this service
    /// that return in no more than `threshold`.
    public var threshold: GoogleCloudWKT.Duration? = nil

    /// Initialize a new instance of `LatencyCriteria`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LatencyCriteria().with { $0.threshold = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.BasicSli.LatencyCriteria"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// This SLI can be evaluated on the basis of availability or latency.
  public enum OneOf_SliCriteria: Codable, Equatable, Sendable {
    /// Good service is defined to be the count of requests made to this service
    /// that return successfully.
    indirect case availability(BasicSli.AvailabilityCriteria?)
    /// Good service is defined to be the count of requests made to this service
    /// that are fast enough with respect to `latency.threshold`.
    indirect case latency(BasicSli.LatencyCriteria?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.BasicSli"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
