// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The protocol for the `CreateAlertPolicy` request.
public struct CreateAlertPolicyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) in which
  /// to create the alerting policy. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///
  /// Note that this field names the parent container in which the alerting
  /// policy will be written, not the name of the created policy. |name| must be
  /// a host project of a Metrics Scope, otherwise INVALID_ARGUMENT error will
  /// return. The alerting policy that is returned will have a name that contains
  /// a normalized representation of this name as a prefix but adds a suffix of
  /// the form `/alertPolicies/[ALERT_POLICY_ID]`, identifying the policy in the
  /// container.
  public var name: Swift.String = Swift.String()

  /// Required. The requested alerting policy. You should omit the `name` field
  /// in this policy. The name will be returned in the new policy, including a
  /// new `[ALERT_POLICY_ID]` value.
  public var alertPolicy: AlertPolicy? = nil

  /// Initialize a new instance of `CreateAlertPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAlertPolicyRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.CreateAlertPolicyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
