// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The `CreateServiceLevelObjective` request.
public struct CreateServiceLevelObjectiveRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name of the parent `Service`. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/services/[SERVICE_ID]
  public var parent: Swift.String = Swift.String()

  /// Optional. The ServiceLevelObjective id to use for this
  /// ServiceLevelObjective. If omitted, an id will be generated instead. Must
  /// match the pattern `^[a-zA-Z0-9-_:.]+$`
  public var serviceLevelObjectiveId: Swift.String = Swift.String()

  /// Required. The `ServiceLevelObjective` to create.
  /// The provided `name` will be respected if no `ServiceLevelObjective` exists
  /// with this name.
  public var serviceLevelObjective: ServiceLevelObjective? = nil

  /// Initialize a new instance of `CreateServiceLevelObjectiveRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateServiceLevelObjectiveRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.CreateServiceLevelObjectiveRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
