// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The `GetNotificationChannelVerificationCode` request.
public struct GetNotificationChannelVerificationCodeResponse: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// The verification code, which may be used to verify other channels
  /// that have an equivalent identity (i.e. other channels of the same
  /// type with the same fingerprint such as other email channels with
  /// the same email address or other sms channels with the same number).
  public var code: Swift.String = Swift.String()

  /// The expiration time associated with the code that was returned. If
  /// an expiration was provided in the request, this is the minimum of the
  /// requested expiration in the request and the max permitted expiration.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `GetNotificationChannelVerificationCodeResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetNotificationChannelVerificationCodeResponse().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.GetNotificationChannelVerificationCodeResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
