// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWKT
import GoogleCloudGax

/// The Group API lets you inspect and manage your
/// [groups](#google.monitoring.v3.Group).
///
/// A group is a named filter that is used to identify
/// a collection of monitored resources. Groups are typically used to
/// mirror the physical and/or logical topology of the environment.
/// Because group membership is computed dynamically, monitored
/// resources that are started in the future are automatically placed
/// in matching groups. By using a group to name monitored resources in,
/// for example, an alert policy, the target of that alert policy is
/// updated automatically as monitored resources are added and removed
/// from the infrastructure.
///
/// @Snippet(path: "GroupServiceQuickstart")
public final class GroupServiceClient: Clients.GroupServiceProtocol, Sendable {
  let inner: any Clients.GroupServiceStub

  /// Creates a new `GroupServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.GroupServiceStub = try Clients.GroupServiceTransport(options)
    inner = Clients.GroupServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.GroupServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists the existing groups.
  ///
  /// @Snippet(path: "GroupService_ListGroups")
  public func listGroups(
    request: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListGroupsResponse {
    try await self.inner.listGroups(request: request, options: options)
  }

  /// Lists the existing groups.
  ///
  /// @Snippet(path: "GroupService_ListGroups")
  public func listGroups(
    byItem: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Group, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMonitoringV3.ListGroupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGroups(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a single group.
  ///
  /// @Snippet(path: "GroupService_GetGroup")
  public func getGroup(
    request: GetGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Group {
    try await self.inner.getGroup(request: request, options: options)
  }

  /// Creates a new group.
  ///
  /// @Snippet(path: "GroupService_CreateGroup")
  public func createGroup(
    request: CreateGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Group {
    try await self.inner.createGroup(request: request, options: options)
  }

  /// Updates an existing group.
  /// You can change any group attributes except `name`.
  ///
  /// @Snippet(path: "GroupService_UpdateGroup")
  public func updateGroup(
    request: UpdateGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Group {
    try await self.inner.updateGroup(request: request, options: options)
  }

  /// Deletes an existing group.
  ///
  /// @Snippet(path: "GroupService_DeleteGroup")
  public func deleteGroup(
    request: DeleteGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteGroup(request: request, options: options)
  }

  /// Lists the monitored resources that are members of a group.
  ///
  /// @Snippet(path: "GroupService_ListGroupMembers")
  public func listGroupMembers(
    request: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListGroupMembersResponse {
    try await self.inner.listGroupMembers(request: request, options: options)
  }

  /// Lists the monitored resources that are members of a group.
  ///
  /// @Snippet(path: "GroupService_ListGroupMembers")
  public func listGroupMembers(
    byItem: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMonitoringV3.ListGroupMembersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGroupMembers(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }
}

extension Clients {
  /// A Swift protocol to mock `GroupServiceClient`.
  ///
  /// To mock `GroupServiceClient` change your functions to receive
  /// `some GroupServiceProtocol` or `any GroupServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol GroupServiceProtocol {
    /// See `GroupServiceClient.listGroups`.
    func listGroups(request: ListGroupsRequest) async throws
      -> GoogleCloudMonitoringV3.ListGroupsResponse

    /// See `GroupServiceClient.listGroups`.
    func listGroups(
      byItem: ListGroupsRequest
    ) throws -> any AsyncSequence<Group, Swift.Error>

    /// See `GroupServiceClient.listGroups`.
    func listGroups(
      name: Swift.String,
    ) throws -> any AsyncSequence<Group, Swift.Error>

    /// See `GroupServiceClient.getGroup`.
    func getGroup(request: GetGroupRequest) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.getGroup`.
    func getGroup(
      name: Swift.String,
    ) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.createGroup`.
    func createGroup(request: CreateGroupRequest) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.createGroup`.
    func createGroup(
      name: Swift.String,
      group: Group?,
    ) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.updateGroup`.
    func updateGroup(request: UpdateGroupRequest) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.updateGroup`.
    func updateGroup(
      group: Group?,
    ) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.deleteGroup`.
    func deleteGroup(request: DeleteGroupRequest) async throws

    /// See `GroupServiceClient.deleteGroup`.
    func deleteGroup(
      name: Swift.String,
    ) async throws

    /// See `GroupServiceClient.listGroupMembers`.
    func listGroupMembers(request: ListGroupMembersRequest) async throws
      -> GoogleCloudMonitoringV3.ListGroupMembersResponse

    /// See `GroupServiceClient.listGroupMembers`.
    func listGroupMembers(
      byItem: ListGroupMembersRequest
    ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error>

    /// See `GroupServiceClient.listGroupMembers`.
    func listGroupMembers(
      name: Swift.String,
    ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error>

    /// See `GroupServiceClient.listGroups`.
    func listGroups(
      request: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListGroupsResponse

    /// See `GroupServiceClient.listGroups`.
    func listGroups(
      byItem: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Group, Swift.Error>

    /// See `GroupServiceClient.getGroup`.
    func getGroup(
      request: GetGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.createGroup`.
    func createGroup(
      request: CreateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.updateGroup`.
    func updateGroup(
      request: UpdateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Group

    /// See `GroupServiceClient.deleteGroup`.
    func deleteGroup(
      request: DeleteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `GroupServiceClient.listGroupMembers`.
    func listGroupMembers(
      request: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListGroupMembersResponse

    /// See `GroupServiceClient.listGroupMembers`.
    func listGroupMembers(
      byItem: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error>
  }
}

// Default implementations
extension Clients.GroupServiceProtocol {
  public func listGroups(request: ListGroupsRequest) async throws
    -> GoogleCloudMonitoringV3.ListGroupsResponse
  {
    try await self.listGroups(request: request, options: .init())
  }

  public func listGroups(
    request: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListGroupsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listGroups(
    byItem: ListGroupsRequest
  ) throws -> any AsyncSequence<Group, Swift.Error> {
    try self.listGroups(byItem: byItem, options: .init())
  }

  public func listGroups(
    byItem: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Group, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMonitoringV3.ListGroupsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGroups(
    name: Swift.String,
  ) throws -> any AsyncSequence<Group, Swift.Error> {
    let request = ListGroupsRequest().with {
      $0.name = name
    }
    return try self.listGroups(byItem: request)
  }

  public func getGroup(request: GetGroupRequest) async throws -> GoogleCloudMonitoringV3.Group {
    try await self.getGroup(request: request, options: .init())
  }

  public func getGroup(
    request: GetGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Group {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getGroup(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringV3.Group {
    let request = GetGroupRequest().with {
      $0.name = name
    }
    return try await self.getGroup(request: request)
  }

  public func createGroup(request: CreateGroupRequest) async throws -> GoogleCloudMonitoringV3.Group
  {
    try await self.createGroup(request: request, options: .init())
  }

  public func createGroup(
    request: CreateGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Group {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createGroup(
    name: Swift.String,
    group: Group?,
  ) async throws -> GoogleCloudMonitoringV3.Group {
    let request = CreateGroupRequest().with {
      $0.name = name
      $0.group = group
    }
    return try await self.createGroup(request: request)
  }

  public func updateGroup(request: UpdateGroupRequest) async throws -> GoogleCloudMonitoringV3.Group
  {
    try await self.updateGroup(request: request, options: .init())
  }

  public func updateGroup(
    request: UpdateGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Group {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateGroup(
    group: Group?,
  ) async throws -> GoogleCloudMonitoringV3.Group {
    let request = UpdateGroupRequest().with {
      $0.group = group
    }
    return try await self.updateGroup(request: request)
  }

  public func deleteGroup(request: DeleteGroupRequest) async throws {
    try await self.deleteGroup(request: request, options: .init())
  }

  public func deleteGroup(
    request: DeleteGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteGroup(
    name: Swift.String,
  ) async throws {
    let request = DeleteGroupRequest().with {
      $0.name = name
    }
    try await self.deleteGroup(request: request)
  }

  public func listGroupMembers(request: ListGroupMembersRequest) async throws
    -> GoogleCloudMonitoringV3.ListGroupMembersResponse
  {
    try await self.listGroupMembers(request: request, options: .init())
  }

  public func listGroupMembers(
    request: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListGroupMembersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listGroupMembers(
    byItem: ListGroupMembersRequest
  ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error> {
    try self.listGroupMembers(byItem: byItem, options: .init())
  }

  public func listGroupMembers(
    byItem: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMonitoringV3.ListGroupMembersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGroupMembers(
    name: Swift.String,
  ) throws -> any AsyncSequence<GoogleApi.MonitoredResource, Swift.Error> {
    let request = ListGroupMembersRequest().with {
      $0.name = name
    }
    return try self.listGroupMembers(byItem: request)
  }
}
