// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An internal checker allows Uptime checks to run on private/internal GCP
/// resources.
@available(*, deprecated)
public struct InternalChecker: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A unique resource name for this InternalChecker. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/internalCheckers/[INTERNAL_CHECKER_ID]
  ///
  /// `[PROJECT_ID_OR_NUMBER]` is the Cloud Monitoring Metrics Scope project for
  /// the Uptime check config associated with the internal checker.
  public var name: Swift.String = Swift.String()

  /// The checker's human-readable name. The display name
  /// should be unique within a Cloud Monitoring Metrics Scope in order to make
  /// it easier to identify; however, uniqueness is not enforced.
  public var displayName: Swift.String = Swift.String()

  /// The [GCP VPC network](https://cloud.google.com/vpc/docs/vpc) where the
  /// internal resource lives (ex: "default").
  public var network: Swift.String = Swift.String()

  /// The GCP zone the Uptime check should egress from. Only respected for
  /// internal Uptime checks, where internal_network is specified.
  public var gcpZone: Swift.String = Swift.String()

  /// The GCP project ID where the internal checker lives. Not necessary
  /// the same as the Metrics Scope project.
  public var peerProjectId: Swift.String = Swift.String()

  /// The current operational state of the internal checker.
  public var state: InternalChecker.State = InternalChecker.State()

  /// Initialize a new instance of `InternalChecker`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InternalChecker().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Operational states for an internal checker.
  public enum State: Codable, Equatable, Sendable {
    /// An internal checker should never be in the unspecified state.
    case unspecified
    /// The checker is being created, provisioned, and configured. A checker in
    /// this state can be returned by `ListInternalCheckers` or
    /// `GetInternalChecker`, as well as by examining the [long running
    /// Operation](https://cloud.google.com/apis/design/design_patterns#long_running_operations)
    /// that created it.
    case creating
    /// The checker is running and available for use. A checker in this state
    /// can be returned by `ListInternalCheckers` or `GetInternalChecker` as
    /// well as by examining the [long running
    /// Operation](https://cloud.google.com/apis/design/design_patterns#long_running_operations)
    /// that created it.
    /// If a checker is being torn down, it is neither visible nor usable, so
    /// there is no "deleting" or "down" state.
    case running
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .running: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .creating: return "CREATING"
      case .running: return "RUNNING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "RUNNING": self = .running
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .running
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .running: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.InternalChecker"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
