// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The message definition for listing `Snooze`s associated with the given
/// `parent`, satisfying the optional `filter`.
public struct ListSnoozesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) whose
  /// `Snooze`s should be listed. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  public var parent: Swift.String = Swift.String()

  /// Optional. Optional filter to restrict results to the given criteria. The
  /// following fields are supported.
  ///
  ///   * `interval.start_time`
  ///   * `interval.end_time`
  ///
  /// For example:
  ///
  ///     interval.start_time > "2022-03-11T00:00:00-08:00" AND
  ///         interval.end_time < "2022-03-12T00:00:00-08:00"
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of results to return for a single query. The
  /// server may further constrain the maximum number of results returned in a
  /// single page. The value should be in the range [1, 1000]. If the value given
  /// is outside this range, the server will decide the number of results to be
  /// returned.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The `next_page_token` from a previous call to
  /// `ListSnoozesRequest` to get the next page of results.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListSnoozesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListSnoozesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListSnoozesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
