// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The protocol for the `ListUptimeCheckConfigs` response.
public struct ListUptimeCheckConfigsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The returned Uptime check configurations.
  public var uptimeCheckConfigs: [UptimeCheckConfig] = []

  /// This field represents the pagination token to retrieve the next page of
  /// results. If the value is empty, it means no further results for the
  /// request. To retrieve the next page of results, the value of the
  /// next_page_token is passed to the subsequent List method call (in the
  /// request message's page_token field).
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of Uptime check configurations for the project,
  /// irrespective of any pagination.
  public var totalSize: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `ListUptimeCheckConfigsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListUptimeCheckConfigsResponse().with { $0.uptimeCheckConfigs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListUptimeCheckConfigsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [UptimeCheckConfig] {
    return self.uptimeCheckConfigs
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
