// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The `ListServices` request.
public struct ListServicesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the parent containing the listed services,
  /// either a [project](https://cloud.google.com/monitoring/api/v3#project_name)
  /// or a Monitoring Metrics Scope. The formats are:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///     workspaces/[HOST_PROJECT_ID_OR_NUMBER]
  public var parent: Swift.String = Swift.String()

  /// A filter specifying what `Service`s to return. The filter supports
  /// filtering on a particular service-identifier type or one of its attributes.
  ///
  /// To filter on a particular service-identifier type, the `identifier_case`
  /// refers to which option in the `identifier` field is populated. For example,
  /// the filter `identifier_case = "CUSTOM"` would match all services with a
  /// value for the `custom` field. Valid options include "CUSTOM", "APP_ENGINE",
  /// "MESH_ISTIO", and the other options listed at
  /// https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services#Service
  ///
  /// To filter on an attribute of a service-identifier type, apply the filter
  /// name by using the snake case of the service-identifier type and the
  /// attribute of that service-identifier type, and join the two with a period.
  /// For example, to filter by the `meshUid` field of the `MeshIstio`
  /// service-identifier type, you must filter on `mesh_istio.mesh_uid =
  /// "123"` to match all services with mesh UID "123". Service-identifier types
  /// and their attributes are described at
  /// https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services#Service
  public var filter: Swift.String = Swift.String()

  /// A non-negative number that is the maximum number of results to return.
  /// When 0, use default page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListServicesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListServicesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListServicesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
