// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWKT
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class MetricServiceRetry: MetricServiceStub {
    let inner: any MetricServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any MetricServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMonitoredResourceDescriptorsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse
          in
          return try await self.inner.listMonitoredResourceDescriptors(request: r, options: o)
        })
    }

    public func getMonitoredResourceDescriptor(
      request: GetMonitoredResourceDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MonitoredResourceDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMonitoredResourceDescriptorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.MonitoredResourceDescriptor
          in
          return try await self.inner.getMonitoredResourceDescriptor(request: r, options: o)
        })
    }

    public func listMetricDescriptors(
      request: ListMetricDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMetricDescriptorsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse
          in
          return try await self.inner.listMetricDescriptors(request: r, options: o)
        })
    }

    public func getMetricDescriptor(
      request: GetMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMetricDescriptorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.MetricDescriptor
          in
          return try await self.inner.getMetricDescriptor(request: r, options: o)
        })
    }

    public func createMetricDescriptor(
      request: CreateMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMetricDescriptorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.MetricDescriptor
          in
          return try await self.inner.createMetricDescriptor(request: r, options: o)
        })
    }

    public func deleteMetricDescriptor(
      request: DeleteMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMetricDescriptorRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteMetricDescriptor(request: r, options: o)
        })
    }

    public func listTimeSeries(
      request: ListTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTimeSeriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListTimeSeriesResponse
          in
          return try await self.inner.listTimeSeries(request: r, options: o)
        })
    }

    public func createTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTimeSeriesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.createTimeSeries(request: r, options: o)
        })
    }

    public func createServiceTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTimeSeriesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.createServiceTimeSeries(request: r, options: o)
        })
    }
  }
}
