// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class MetricServiceLogging: MetricServiceStub {
    let inner: any MetricServiceStub
    let logger: Logger

    public init(_ inner: any MetricServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-monitoring-v3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "MetricService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMonitoredResourceDescriptors",
        action: {
          (r: ListMonitoredResourceDescriptorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse
          in
          return try await self.inner.listMonitoredResourceDescriptors(request: r, options: o)
        })
    }

    public func getMonitoredResourceDescriptor(
      request: GetMonitoredResourceDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.MonitoredResourceDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMonitoredResourceDescriptor",
        action: {
          (r: GetMonitoredResourceDescriptorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApi.MonitoredResourceDescriptor
          in
          return try await self.inner.getMonitoredResourceDescriptor(request: r, options: o)
        })
    }

    public func listMetricDescriptors(
      request: ListMetricDescriptorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMetricDescriptors",
        action: {
          (r: ListMetricDescriptorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse
          in
          return try await self.inner.listMetricDescriptors(request: r, options: o)
        })
    }

    public func getMetricDescriptor(
      request: GetMetricDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMetricDescriptor",
        action: {
          (r: GetMetricDescriptorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApi.MetricDescriptor
          in
          return try await self.inner.getMetricDescriptor(request: r, options: o)
        })
    }

    public func createMetricDescriptor(
      request: CreateMetricDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMetricDescriptor",
        action: {
          (r: CreateMetricDescriptorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApi.MetricDescriptor
          in
          return try await self.inner.createMetricDescriptor(request: r, options: o)
        })
    }

    public func deleteMetricDescriptor(
      request: DeleteMetricDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMetricDescriptor",
        action: {
          (r: DeleteMetricDescriptorRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteMetricDescriptor(request: r, options: o)
        })
    }

    public func listTimeSeries(
      request: ListTimeSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTimeSeries",
        action: {
          (r: ListTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListTimeSeriesResponse
          in
          return try await self.inner.listTimeSeries(request: r, options: o)
        })
    }

    public func createTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTimeSeries",
        action: { (r: CreateTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.createTimeSeries(request: r, options: o)
        })
    }

    public func createServiceTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceTimeSeries",
        action: { (r: CreateTimeSeriesRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.createServiceTimeSeries(request: r, options: o)
        })
    }
  }
}
