// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol MetricServiceStub: Sendable {
    func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse

    func getMonitoredResourceDescriptor(
      request: GetMonitoredResourceDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MonitoredResourceDescriptor

    func listMetricDescriptors(
      request: ListMetricDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse

    func getMetricDescriptor(
      request: GetMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor

    func createMetricDescriptor(
      request: CreateMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor

    func deleteMetricDescriptor(
      request: DeleteMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listTimeSeries(
      request: ListTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse

    func createTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createServiceTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
