// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class NotificationChannelServiceRetry: NotificationChannelServiceStub {
    let inner: any NotificationChannelServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any NotificationChannelServiceStub, options: GoogleCloudGax.ClientOptions)
    {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listNotificationChannelDescriptors(
      request: ListNotificationChannelDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListNotificationChannelDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListNotificationChannelDescriptorsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudMonitoringV3.ListNotificationChannelDescriptorsResponse
          in
          return try await self.inner.listNotificationChannelDescriptors(request: r, options: o)
        })
    }

    public func getNotificationChannelDescriptor(
      request: GetNotificationChannelDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.NotificationChannelDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetNotificationChannelDescriptorRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudMonitoringV3.NotificationChannelDescriptor
          in
          return try await self.inner.getNotificationChannelDescriptor(request: r, options: o)
        })
    }

    public func listNotificationChannels(
      request: ListNotificationChannelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListNotificationChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListNotificationChannelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListNotificationChannelsResponse
          in
          return try await self.inner.listNotificationChannels(request: r, options: o)
        })
    }

    public func getNotificationChannel(
      request: GetNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.NotificationChannel
          in
          return try await self.inner.getNotificationChannel(request: r, options: o)
        })
    }

    public func createNotificationChannel(
      request: CreateNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.NotificationChannel
          in
          return try await self.inner.createNotificationChannel(request: r, options: o)
        })
    }

    public func updateNotificationChannel(
      request: UpdateNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.NotificationChannel
          in
          return try await self.inner.updateNotificationChannel(request: r, options: o)
        })
    }

    public func deleteNotificationChannel(
      request: DeleteNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteNotificationChannel(request: r, options: o)
        })
    }

    public func sendNotificationChannelVerificationCode(
      request: SendNotificationChannelVerificationCodeRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SendNotificationChannelVerificationCodeRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.sendNotificationChannelVerificationCode(
            request: r, options: o)
        })
    }

    public func getNotificationChannelVerificationCode(
      request: GetNotificationChannelVerificationCodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.GetNotificationChannelVerificationCodeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GetNotificationChannelVerificationCodeRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudMonitoringV3.GetNotificationChannelVerificationCodeResponse
          in
          return try await self.inner.getNotificationChannelVerificationCode(request: r, options: o)
        })
    }

    public func verifyNotificationChannel(
      request: VerifyNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: VerifyNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.NotificationChannel
          in
          return try await self.inner.verifyNotificationChannel(request: r, options: o)
        })
    }
  }
}
