// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A single data point in a time series.
public struct Point: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The time interval to which the data point applies.  For `GAUGE` metrics,
  /// the start time is optional, but if it is supplied, it must equal the
  /// end time.  For `DELTA` metrics, the start
  /// and end time should specify a non-zero interval, with subsequent points
  /// specifying contiguous and non-overlapping intervals.  For `CUMULATIVE`
  /// metrics, the start and end time should specify a non-zero interval, with
  /// subsequent points specifying the same start time and increasing end times,
  /// until an event resets the cumulative value to zero and sets a new start
  /// time for the following points.
  public var interval: TimeInterval? = nil

  /// The value of the data point.
  public var value: TypedValue? = nil

  /// Initialize a new instance of `Point`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Point().with { $0.interval = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.Point"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
