// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ServiceMonitoringServiceLogging: ServiceMonitoringServiceStub {
    let inner: any ServiceMonitoringServiceStub
    let logger: Logger

    public init(_ inner: any ServiceMonitoringServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-monitoring-v3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ServiceMonitoringService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createService(
      request: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "createService",
        action: {
          (r: CreateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.Service
          in
          return try await self.inner.createService(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "getService",
        action: {
          (r: GetServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.Service
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServices",
        action: {
          (r: ListServicesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func updateService(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateService",
        action: {
          (r: UpdateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.Service
          in
          return try await self.inner.updateService(request: r, options: o)
        })
    }

    public func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteService",
        action: { (r: DeleteServiceRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteService(request: r, options: o)
        })
    }

    public func createServiceLevelObjective(
      request: CreateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceLevelObjective",
        action: {
          (r: CreateServiceLevelObjectiveRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ServiceLevelObjective
          in
          return try await self.inner.createServiceLevelObjective(request: r, options: o)
        })
    }

    public func getServiceLevelObjective(
      request: GetServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceLevelObjective",
        action: {
          (r: GetServiceLevelObjectiveRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ServiceLevelObjective
          in
          return try await self.inner.getServiceLevelObjective(request: r, options: o)
        })
    }

    public func listServiceLevelObjectives(
      request: ListServiceLevelObjectivesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceLevelObjectives",
        action: {
          (r: ListServiceLevelObjectivesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse
          in
          return try await self.inner.listServiceLevelObjectives(request: r, options: o)
        })
    }

    public func updateServiceLevelObjective(
      request: UpdateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateServiceLevelObjective",
        action: {
          (r: UpdateServiceLevelObjectiveRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ServiceLevelObjective
          in
          return try await self.inner.updateServiceLevelObjective(request: r, options: o)
        })
    }

    public func deleteServiceLevelObjective(
      request: DeleteServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceLevelObjective",
        action: {
          (r: DeleteServiceLevelObjectiveRequest, o: GoogleGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteServiceLevelObjective(request: r, options: o)
        })
    }
  }
}
