// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes a Synthetic Monitor to be invoked by Uptime.
public struct SyntheticMonitorTarget: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Specifies a Synthetic Monitor's execution stack.
  public var target: OneOf_Target? = nil

  /// Initialize a new instance of `SyntheticMonitorTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SyntheticMonitorTarget().with { $0.cloudFunctionV2 = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudFunctionV2 = "cloudFunctionV2"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var target: OneOf_Target? = nil
    let targetCheckAndSet = {
      if target != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'target'"))
      }
      target = $0
    }
    if let cloudFunctionV2 = try container.decodeIfPresent(
      SyntheticMonitorTarget.CloudFunctionV2Target?.self, forKey: .cloudFunctionV2)
    {
      try targetCheckAndSet(.cloudFunctionV2(cloudFunctionV2))
    }
    self.target = target
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.target {
      switch choice {
      case .cloudFunctionV2(let value):
        try container.encode(value, forKey: .cloudFunctionV2)
      }
    }
  }

  /// A Synthetic Monitor deployed to a Cloud Functions V2 instance.
  public struct CloudFunctionV2Target: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Fully qualified GCFv2 resource name
    /// i.e. `projects/{project}/locations/{location}/functions/{function}`
    /// Required.
    public var name: Swift.String = Swift.String()

    /// Output only. The `cloud_run_revision` Monitored Resource associated with
    /// the GCFv2. The Synthetic Monitor execution results (metrics, logs, and
    /// spans) are reported against this Monitored Resource. This field is output
    /// only.
    public var cloudRunRevision: GoogleApi.MonitoredResource? = nil

    /// Initialize a new instance of `CloudFunctionV2Target`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudFunctionV2Target().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.SyntheticMonitorTarget.CloudFunctionV2Target"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Specifies a Synthetic Monitor's execution stack.
  public enum OneOf_Target: Codable, Equatable, Sendable {
    /// Target a Synthetic Monitor GCFv2 instance.
    indirect case cloudFunctionV2(SyntheticMonitorTarget.CloudFunctionV2Target?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.SyntheticMonitorTarget"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
