// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A collection of data points that describes the time-varying values
/// of a metric. A time series is identified by a combination of a
/// fully-specified monitored resource and a fully-specified metric.
/// This type is used for both listing and creating time series.
public struct TimeSeries: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The associated metric. A fully-specified metric used to identify the time
  /// series.
  public var metric: GoogleApi.Metric? = nil

  /// The associated monitored resource.  Custom metrics can use only certain
  /// monitored resource types in their time series data. For more information,
  /// see [Monitored resources for custom
  /// metrics](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#custom-metric-resources).
  public var resource: GoogleApi.MonitoredResource? = nil

  /// Output only. The associated monitored resource metadata. When reading a
  /// time series, this field will include metadata labels that are explicitly
  /// named in the reduction. When creating a time series, this field is ignored.
  public var metadata: GoogleApi.MonitoredResourceMetadata? = nil

  /// The metric kind of the time series. When listing time series, this metric
  /// kind might be different from the metric kind of the associated metric if
  /// this time series is an alignment or reduction of other time series.
  ///
  /// When creating a time series, this field is optional. If present, it must be
  /// the same as the metric kind of the associated metric. If the associated
  /// metric's descriptor must be auto-created, then this field specifies the
  /// metric kind of the new descriptor and must be either `GAUGE` (the default)
  /// or `CUMULATIVE`.
  public var metricKind: GoogleApi.MetricDescriptor.MetricKind = GoogleApi.MetricDescriptor
    .MetricKind()

  /// The value type of the time series. When listing time series, this value
  /// type might be different from the value type of the associated metric if
  /// this time series is an alignment or reduction of other time series.
  ///
  /// When creating a time series, this field is optional. If present, it must be
  /// the same as the type of the data in the `points` field.
  public var valueType: GoogleApi.MetricDescriptor.ValueType = GoogleApi.MetricDescriptor
    .ValueType()

  /// The data points of this time series. When listing time series, points are
  /// returned in reverse time order.
  ///
  /// When creating a time series, this field must contain exactly one point and
  /// the point's type must be the same as the value type of the associated
  /// metric. If the associated metric's descriptor must be auto-created, then
  /// the value type of the descriptor is determined by the point's type, which
  /// must be `BOOL`, `INT64`, `DOUBLE`, or `DISTRIBUTION`.
  public var points: [Point] = []

  /// The units in which the metric value is reported. It is only applicable
  /// if the `value_type` is `INT64`, `DOUBLE`, or `DISTRIBUTION`. The `unit`
  /// defines the representation of the stored metric values. This field can only
  /// be changed through CreateTimeSeries when it is empty.
  public var unit: Swift.String = Swift.String()

  /// Input only. A detailed description of the time series that will be
  /// associated with the
  /// [google.api.MetricDescriptor][google.api.MetricDescriptor] for the metric.
  /// Once set, this field cannot be changed through CreateTimeSeries.
  ///
  /// [google.api.MetricDescriptor]: https://www.google.com/search?q=Swift+google.api+GoogleApi.MetricDescriptor
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `TimeSeries`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeries().with { $0.metric = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.TimeSeries"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
