// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A descriptor for the labels and points in a time series.
public struct TimeSeriesDescriptor: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Descriptors for the labels.
  public var labelDescriptors: [GoogleApi.LabelDescriptor] = []

  /// Descriptors for the point data value columns.
  public var pointDescriptors: [TimeSeriesDescriptor.ValueDescriptor] = []

  /// Initialize a new instance of `TimeSeriesDescriptor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeriesDescriptor().with { $0.labelDescriptors = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A descriptor for the value columns in a data point.
  public struct ValueDescriptor: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The value key.
    public var key: Swift.String = Swift.String()

    /// The value type.
    public var valueType: GoogleApi.MetricDescriptor.ValueType = GoogleApi.MetricDescriptor
      .ValueType()

    /// The value stream kind.
    public var metricKind: GoogleApi.MetricDescriptor.MetricKind = GoogleApi.MetricDescriptor
      .MetricKind()

    /// The unit in which `time_series` point values are reported. `unit`
    /// follows the UCUM format for units as seen in
    /// https://unitsofmeasure.org/ucum.html.
    /// `unit` is only valid if `value_type` is INTEGER, DOUBLE, DISTRIBUTION.
    public var unit: Swift.String = Swift.String()

    /// Initialize a new instance of `ValueDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ValueDescriptor().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.TimeSeriesDescriptor.ValueDescriptor"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.TimeSeriesDescriptor"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
