// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A `TimeSeriesRatio` specifies two `TimeSeries` to use for computing the
/// `good_service / total_service` ratio. The specified `TimeSeries` must have
/// `ValueType = DOUBLE` or `ValueType = INT64` and must have `MetricKind =
/// DELTA` or `MetricKind = CUMULATIVE`. The `TimeSeriesRatio` must specify
/// exactly two of good, bad, and total, and the relationship `good_service +
/// bad_service = total_service` will be assumed.
public struct TimeSeriesRatio: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifying a `TimeSeries` quantifying good service provided. Must have
  /// `ValueType = DOUBLE` or `ValueType = INT64` and must have `MetricKind =
  /// DELTA` or `MetricKind = CUMULATIVE`.
  public var goodServiceFilter: Swift.String = Swift.String()

  /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifying a `TimeSeries` quantifying bad service, either demanded service
  /// that was not provided or demanded service that was of inadequate quality.
  /// Must have `ValueType = DOUBLE` or `ValueType = INT64` and must have
  /// `MetricKind = DELTA` or `MetricKind = CUMULATIVE`.
  public var badServiceFilter: Swift.String = Swift.String()

  /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifying a `TimeSeries` quantifying total demanded service. Must have
  /// `ValueType = DOUBLE` or `ValueType = INT64` and must have `MetricKind =
  /// DELTA` or `MetricKind = CUMULATIVE`.
  public var totalServiceFilter: Swift.String = Swift.String()

  /// Initialize a new instance of `TimeSeriesRatio`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeriesRatio().with { $0.goodServiceFilter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.TimeSeriesRatio"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
