// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class UptimeCheckServiceLogging: UptimeCheckServiceStub {
    let inner: any UptimeCheckServiceStub
    let logger: Logger

    public init(_ inner: any UptimeCheckServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-monitoring-v3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "UptimeCheckService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listUptimeCheckConfigs(
      request: ListUptimeCheckConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listUptimeCheckConfigs",
        action: {
          (r: ListUptimeCheckConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse
          in
          return try await self.inner.listUptimeCheckConfigs(request: r, options: o)
        })
    }

    public func getUptimeCheckConfig(
      request: GetUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getUptimeCheckConfig",
        action: {
          (r: GetUptimeCheckConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.UptimeCheckConfig
          in
          return try await self.inner.getUptimeCheckConfig(request: r, options: o)
        })
    }

    public func createUptimeCheckConfig(
      request: CreateUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createUptimeCheckConfig",
        action: {
          (r: CreateUptimeCheckConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.UptimeCheckConfig
          in
          return try await self.inner.createUptimeCheckConfig(request: r, options: o)
        })
    }

    public func updateUptimeCheckConfig(
      request: UpdateUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateUptimeCheckConfig",
        action: {
          (r: UpdateUptimeCheckConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.UptimeCheckConfig
          in
          return try await self.inner.updateUptimeCheckConfig(request: r, options: o)
        })
    }

    public func deleteUptimeCheckConfig(
      request: DeleteUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteUptimeCheckConfig",
        action: {
          (r: DeleteUptimeCheckConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteUptimeCheckConfig(request: r, options: o)
        })
    }

    public func listUptimeCheckIps(
      request: ListUptimeCheckIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listUptimeCheckIps",
        action: {
          (r: ListUptimeCheckIpsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse
          in
          return try await self.inner.listUptimeCheckIps(request: r, options: o)
        })
    }
  }
}
