// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A `WindowsBasedSli` defines `good_service` as the count of time windows for
/// which the provided service was of good quality. Criteria for determining
/// if service was good are embedded in the `window_criterion`.
public struct WindowsBasedSli: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Duration over which window quality is evaluated. Must be an integer
  /// fraction of a day and at least `60s`.
  public var windowPeriod: GoogleCloudWkt.Duration? = nil

  /// The criterion to use for evaluating window goodness.
  public var windowCriterion: OneOf_WindowCriterion? = nil

  /// Initialize a new instance of `WindowsBasedSli`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WindowsBasedSli().with { $0.goodBadMetricFilter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case goodBadMetricFilter = "goodBadMetricFilter"
    case goodTotalRatioThreshold = "goodTotalRatioThreshold"
    case metricMeanInRange = "metricMeanInRange"
    case metricSumInRange = "metricSumInRange"
    case windowPeriod = "windowPeriod"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.windowPeriod = try container.decodeIfPresent(
      GoogleCloudWkt.Duration.self, forKey: .windowPeriod)

    var windowCriterion: OneOf_WindowCriterion? = nil
    let windowCriterionCheckAndSet = {
      if windowCriterion != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'windowCriterion'"))
      }
      windowCriterion = $0
    }
    if let goodBadMetricFilter = try container.decodeIfPresent(
      Swift.String.self, forKey: .goodBadMetricFilter)
    {
      try windowCriterionCheckAndSet(.goodBadMetricFilter(goodBadMetricFilter))
    }
    if let goodTotalRatioThreshold = try container.decodeIfPresent(
      WindowsBasedSli.PerformanceThreshold?.self, forKey: .goodTotalRatioThreshold)
    {
      try windowCriterionCheckAndSet(.goodTotalRatioThreshold(goodTotalRatioThreshold))
    }
    if let metricMeanInRange = try container.decodeIfPresent(
      WindowsBasedSli.MetricRange?.self, forKey: .metricMeanInRange)
    {
      try windowCriterionCheckAndSet(.metricMeanInRange(metricMeanInRange))
    }
    if let metricSumInRange = try container.decodeIfPresent(
      WindowsBasedSli.MetricRange?.self, forKey: .metricSumInRange)
    {
      try windowCriterionCheckAndSet(.metricSumInRange(metricSumInRange))
    }
    self.windowCriterion = windowCriterion
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.windowPeriod, forKey: .windowPeriod)

    if let choice = self.windowCriterion {
      switch choice {
      case .goodBadMetricFilter(let value):
        try container.encode(value, forKey: .goodBadMetricFilter)
      case .goodTotalRatioThreshold(let value):
        try container.encode(value, forKey: .goodTotalRatioThreshold)
      case .metricMeanInRange(let value):
        try container.encode(value, forKey: .metricMeanInRange)
      case .metricSumInRange(let value):
        try container.encode(value, forKey: .metricSumInRange)
      }
    }
  }

  /// A `PerformanceThreshold` is used when each window is good when that window
  /// has a sufficiently high `performance`.
  public struct PerformanceThreshold: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// If window `performance >= threshold`, the window is counted as good.
    public var threshold: Swift.Double = Swift.Double()

    /// The means, either a request-based SLI or a basic SLI, by which to compute
    /// performance over a window.
    public var type: OneOf_Type_? = nil

    /// Initialize a new instance of `PerformanceThreshold`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PerformanceThreshold().with { $0.performance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case performance = "performance"
      case basicSliPerformance = "basicSliPerformance"
      case threshold = "threshold"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.threshold = try container.decode(Swift.Double.self, forKey: .threshold)

      var type: OneOf_Type_? = nil
      let typeCheckAndSet = {
        if type != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'type'"))
        }
        type = $0
      }
      if let performance = try container.decodeIfPresent(
        RequestBasedSli?.self, forKey: .performance)
      {
        try typeCheckAndSet(.performance(performance))
      }
      if let basicSliPerformance = try container.decodeIfPresent(
        BasicSli?.self, forKey: .basicSliPerformance)
      {
        try typeCheckAndSet(.basicSliPerformance(basicSliPerformance))
      }
      self.type = type
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.threshold, forKey: .threshold)

      if let choice = self.type {
        switch choice {
        case .performance(let value):
          try container.encode(value, forKey: .performance)
        case .basicSliPerformance(let value):
          try container.encode(value, forKey: .basicSliPerformance)
        }
      }
    }

    /// The means, either a request-based SLI or a basic SLI, by which to compute
    /// performance over a window.
    public enum OneOf_Type_: Codable, Equatable, Sendable {
      /// `RequestBasedSli` to evaluate to judge window quality.
      indirect case performance(RequestBasedSli?)
      /// `BasicSli` to evaluate to judge window quality.
      indirect case basicSliPerformance(BasicSli?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.WindowsBasedSli.PerformanceThreshold"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A `MetricRange` is used when each window is good when the value x of a
  /// single `TimeSeries` satisfies `range.min <= x <= range.max`. The provided
  /// `TimeSeries` must have `ValueType = INT64` or `ValueType = DOUBLE` and
  /// `MetricKind = GAUGE`.
  public struct MetricRange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
    /// specifying the `TimeSeries` to use for evaluating window quality.
    public var timeSeries: Swift.String = Swift.String()

    /// Range of values considered "good." For a one-sided range, set one bound
    /// to an infinite value.
    public var range: Range? = nil

    /// Initialize a new instance of `MetricRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MetricRange().with { $0.timeSeries = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.WindowsBasedSli.MetricRange"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The criterion to use for evaluating window goodness.
  public enum OneOf_WindowCriterion: Codable, Equatable, Sendable {
    /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
    /// specifying a `TimeSeries` with `ValueType = BOOL`. The window is good if
    /// any `true` values appear in the window.
    case goodBadMetricFilter(Swift.String)
    /// A window is good if its `performance` is high enough.
    indirect case goodTotalRatioThreshold(WindowsBasedSli.PerformanceThreshold?)
    /// A window is good if the metric's value is in a good range, averaged
    /// across returned streams.
    indirect case metricMeanInRange(WindowsBasedSli.MetricRange?)
    /// A window is good if the metric's value is in a good range, summed across
    /// returned streams.
    indirect case metricSumInRange(WindowsBasedSli.MetricRange?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.WindowsBasedSli"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
