// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class AlertPolicyServiceRetry: AlertPolicyServiceStub {
    let inner: any AlertPolicyServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any AlertPolicyServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listAlertPolicies(
      request: ListAlertPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListAlertPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAlertPoliciesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ListAlertPoliciesResponse
          in
          return try await self.inner.listAlertPolicies(request: r, options: o)
        })
    }

    public func getAlertPolicy(
      request: GetAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.AlertPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.AlertPolicy
          in
          return try await self.inner.getAlertPolicy(request: r, options: o)
        })
    }

    public func createAlertPolicy(
      request: CreateAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.AlertPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.AlertPolicy
          in
          return try await self.inner.createAlertPolicy(request: r, options: o)
        })
    }

    public func deleteAlertPolicy(
      request: DeleteAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAlertPolicy(request: r, options: o)
        })
    }

    public func updateAlertPolicy(
      request: UpdateAlertPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.AlertPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAlertPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.AlertPolicy
          in
          return try await self.inner.updateAlertPolicy(request: r, options: o)
        })
    }
  }
}
