// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class GroupServiceLogging: GroupServiceStub {
    let inner: any GroupServiceStub
    let logger: Logger

    public init(_ inner: any GroupServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-monitoring-v3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "GroupService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listGroups(
      request: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGroups",
        action: {
          (r: ListGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ListGroupsResponse
          in
          return try await self.inner.listGroups(request: r, options: o)
        })
    }

    public func getGroup(
      request: GetGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.Group {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGroup",
        action: {
          (r: GetGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.Group
          in
          return try await self.inner.getGroup(request: r, options: o)
        })
    }

    public func createGroup(
      request: CreateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.Group {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGroup",
        action: {
          (r: CreateGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.Group
          in
          return try await self.inner.createGroup(request: r, options: o)
        })
    }

    public func updateGroup(
      request: UpdateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.Group {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGroup",
        action: {
          (r: UpdateGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.Group
          in
          return try await self.inner.updateGroup(request: r, options: o)
        })
    }

    public func deleteGroup(
      request: DeleteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteGroup",
        action: { (r: DeleteGroupRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteGroup(request: r, options: o)
        })
    }

    public func listGroupMembers(
      request: ListGroupMembersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListGroupMembersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGroupMembers",
        action: {
          (r: ListGroupMembersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ListGroupMembersResponse
          in
          return try await self.inner.listGroupMembers(request: r, options: o)
        })
    }
  }
}
