// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The `ListNotificationChannels` request.
public struct ListNotificationChannelsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) on which
  /// to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///
  /// This names the container
  /// in which to look for the notification channels; it does not name a
  /// specific channel. To query a specific channel by REST resource name, use
  /// the
  /// [`GetNotificationChannel`][google.monitoring.v3.NotificationChannelService.GetNotificationChannel]
  /// operation.
  ///
  /// [google.monitoring.v3.NotificationChannelService.GetNotificationChannel]: <doc:NotificationChannelService/getNotificationChannel(request:)>
  public var name: Swift.String = Swift.String()

  /// Optional. If provided, this field specifies the criteria that must be met
  /// by notification channels to be included in the response.
  ///
  /// For more details, see [sorting and
  /// filtering](https://cloud.google.com/monitoring/api/v3/sorting-and-filtering).
  public var filter: Swift.String = Swift.String()

  /// Optional. A comma-separated list of fields by which to sort the result.
  /// Supports the same set of fields as in `filter`. Entries can be prefixed
  /// with a minus sign to sort in descending rather than ascending order.
  ///
  /// For more details, see [sorting and
  /// filtering](https://cloud.google.com/monitoring/api/v3/sorting-and-filtering).
  public var orderBy: Swift.String = Swift.String()

  /// Optional. The maximum number of results to return in a single response. If
  /// not set to a positive number, a reasonable value will be chosen by the
  /// service.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. If non-empty, `page_token` must contain a value returned as the
  /// `next_page_token` in a previous response to request the next set
  /// of results.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListNotificationChannelsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListNotificationChannelsRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListNotificationChannelsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
