// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol MetricServiceStub {
    func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListMonitoredResourceDescriptorsResponse

    func getMonitoredResourceDescriptor(
      request: GetMonitoredResourceDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MonitoredResourceDescriptor

    func listMetricDescriptors(
      request: ListMetricDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListMetricDescriptorsResponse

    func getMetricDescriptor(
      request: GetMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor

    func createMetricDescriptor(
      request: CreateMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor

    func deleteMetricDescriptor(
      request: DeleteMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listTimeSeries(
      request: ListTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListTimeSeriesResponse

    func createTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createServiceTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }

  class MetricServiceTransport: MetricServiceStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://monitoring.googleapis.com")
    }

    public func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListMonitoredResourceDescriptorsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/monitoredResourceDescriptors"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.ListMonitoredResourceDescriptorsResponse.self, from: data)
    }

    public func getMonitoredResourceDescriptor(
      request: GetMonitoredResourceDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MonitoredResourceDescriptor {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.MonitoredResourceDescriptor.self, from: data)
    }

    public func listMetricDescriptors(
      request: ListMetricDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListMetricDescriptorsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/metricDescriptors"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.activeOnly, prefix: "activeOnly"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.ListMetricDescriptorsResponse.self, from: data)
    }

    public func getMetricDescriptor(
      request: GetMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.MetricDescriptor.self, from: data)
    }

    public func createMetricDescriptor(
      request: CreateMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/metricDescriptors"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.metricDescriptor {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.MetricDescriptor.self, from: data)
    }

    public func deleteMetricDescriptor(
      request: DeleteMetricDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func listTimeSeries(
      request: ListTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListTimeSeriesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/timeSeries"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.interval, prefix: "interval"))
      query.append(contentsOf: try encoder.encode(request.aggregation, prefix: "aggregation"))
      query.append(
        contentsOf: try encoder.encode(request.secondaryAggregation, prefix: "secondaryAggregation")
      )
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.ListTimeSeriesResponse.self, from: data)
    }

    public func createTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/timeSeries"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      _ = try await self.inner.rpc(for: req).get()
    }

    public func createServiceTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/timeSeries:createService"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      _ = try await self.inner.rpc(for: req).get()
    }
  }
}
