// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class NotificationChannelServiceLogging: NotificationChannelServiceStub {
    let inner: any NotificationChannelServiceStub
    let logger: Logger

    public init(_ inner: any NotificationChannelServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleMonitoringV3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "NotificationChannelService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listNotificationChannelDescriptors(
      request: ListNotificationChannelDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListNotificationChannelDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNotificationChannelDescriptors",
        action: {
          (r: ListNotificationChannelDescriptorsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleMonitoringV3.ListNotificationChannelDescriptorsResponse
          in
          return try await self.inner.listNotificationChannelDescriptors(request: r, options: o)
        })
    }

    public func getNotificationChannelDescriptor(
      request: GetNotificationChannelDescriptorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.NotificationChannelDescriptor {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNotificationChannelDescriptor",
        action: {
          (r: GetNotificationChannelDescriptorRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleMonitoringV3.NotificationChannelDescriptor
          in
          return try await self.inner.getNotificationChannelDescriptor(request: r, options: o)
        })
    }

    public func listNotificationChannels(
      request: ListNotificationChannelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListNotificationChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNotificationChannels",
        action: {
          (r: ListNotificationChannelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ListNotificationChannelsResponse
          in
          return try await self.inner.listNotificationChannels(request: r, options: o)
        })
    }

    public func getNotificationChannel(
      request: GetNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNotificationChannel",
        action: {
          (r: GetNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.NotificationChannel
          in
          return try await self.inner.getNotificationChannel(request: r, options: o)
        })
    }

    public func createNotificationChannel(
      request: CreateNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNotificationChannel",
        action: {
          (r: CreateNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.NotificationChannel
          in
          return try await self.inner.createNotificationChannel(request: r, options: o)
        })
    }

    public func updateNotificationChannel(
      request: UpdateNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNotificationChannel",
        action: {
          (r: UpdateNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.NotificationChannel
          in
          return try await self.inner.updateNotificationChannel(request: r, options: o)
        })
    }

    public func deleteNotificationChannel(
      request: DeleteNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNotificationChannel",
        action: {
          (r: DeleteNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteNotificationChannel(request: r, options: o)
        })
    }

    public func sendNotificationChannelVerificationCode(
      request: SendNotificationChannelVerificationCodeRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "sendNotificationChannelVerificationCode",
        action: {
          (r: SendNotificationChannelVerificationCodeRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.sendNotificationChannelVerificationCode(
            request: r, options: o)
        })
    }

    public func getNotificationChannelVerificationCode(
      request: GetNotificationChannelVerificationCodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.GetNotificationChannelVerificationCodeResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNotificationChannelVerificationCode",
        action: {
          (r: GetNotificationChannelVerificationCodeRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleMonitoringV3.GetNotificationChannelVerificationCodeResponse
          in
          return try await self.inner.getNotificationChannelVerificationCode(request: r, options: o)
        })
    }

    public func verifyNotificationChannel(
      request: VerifyNotificationChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.NotificationChannel {
      try await self._intercept(
        request: request,
        options: options,
        name: "verifyNotificationChannel",
        action: {
          (r: VerifyNotificationChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.NotificationChannel
          in
          return try await self.inner.verifyNotificationChannel(request: r, options: o)
        })
    }
  }
}
