// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class QueryServiceLogging: QueryServiceStub {
    let inner: any QueryServiceStub
    let logger: Logger

    public init(_ inner: any QueryServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleMonitoringV3"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "QueryService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func queryTimeSeries(
      request: QueryTimeSeriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.QueryTimeSeriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryTimeSeries",
        action: {
          (r: QueryTimeSeriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.QueryTimeSeriesResponse
          in
          return try await self.inner.queryTimeSeries(request: r, options: o)
        })
    }
  }
}
