// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class ServiceMonitoringServiceRetry: ServiceMonitoringServiceStub {
    let inner: any ServiceMonitoringServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ServiceMonitoringServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createService(
      request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.Service
          in
          return try await self.inner.createService(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.Service
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func updateService(
      request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.Service
          in
          return try await self.inner.updateService(request: r, options: o)
        })
    }

    public func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteService(request: r, options: o)
        })
    }

    public func createServiceLevelObjective(
      request: CreateServiceLevelObjectiveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ServiceLevelObjective {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServiceLevelObjectiveRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ServiceLevelObjective
          in
          return try await self.inner.createServiceLevelObjective(request: r, options: o)
        })
    }

    public func getServiceLevelObjective(
      request: GetServiceLevelObjectiveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ServiceLevelObjective {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceLevelObjectiveRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ServiceLevelObjective
          in
          return try await self.inner.getServiceLevelObjective(request: r, options: o)
        })
    }

    public func listServiceLevelObjectives(
      request: ListServiceLevelObjectivesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListServiceLevelObjectivesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServiceLevelObjectivesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ListServiceLevelObjectivesResponse
          in
          return try await self.inner.listServiceLevelObjectives(request: r, options: o)
        })
    }

    public func updateServiceLevelObjective(
      request: UpdateServiceLevelObjectiveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ServiceLevelObjective {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServiceLevelObjectiveRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleMonitoringV3.ServiceLevelObjective
          in
          return try await self.inner.updateServiceLevelObjective(request: r, options: o)
        })
    }

    public func deleteServiceLevelObjective(
      request: DeleteServiceLevelObjectiveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceLevelObjectiveRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteServiceLevelObjective(request: r, options: o)
        })
    }
  }
}
