// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes a time interval:
///
///   * Reads: A half-open time interval. It includes the end time but
///     excludes the start time: `(startTime, endTime]`. The start time
///     must be specified, must be earlier than the end time, and should be
///     no older than the data retention period for the metric.
///   * Writes: A closed time interval. It extends from the start time to the end
///   time,
///     and includes both: `[startTime, endTime]`. Valid time intervals
///     depend on the
///     [`MetricKind`](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#MetricKind)
///     of the metric value. The end time must not be earlier than the start
///     time, and the end time must not be more than 25 hours in the past or more
///     than five minutes in the future.
///     * For `GAUGE` metrics, the `startTime` value is technically optional; if
///       no value is specified, the start time defaults to the value of the
///       end time, and the interval represents a single point in time. If both
///       start and end times are specified, they must be identical. Such an
///       interval is valid only for `GAUGE` metrics, which are point-in-time
///       measurements. The end time of a new interval must be at least a
///       millisecond after the end time of the previous interval.
///     * For `DELTA` metrics, the start time and end time must specify a
///       non-zero interval, with subsequent points specifying contiguous and
///       non-overlapping intervals. For `DELTA` metrics, the start time of
///       the next interval must be at least a millisecond after the end time
///       of the previous interval.
///     * For `CUMULATIVE` metrics, the start time and end time must specify a
///       non-zero interval, with subsequent points specifying the same
///       start time and increasing end times, until an event resets the
///       cumulative value to zero and sets a new start time for the following
///       points. The new start time must be at least a millisecond after the
///       end time of the previous interval.
///     * The start time of a new interval must be at least a millisecond after
///     the
///       end time of the previous interval because intervals are closed. If the
///       start time of a new interval is the same as the end time of the
///       previous interval, then data written at the new start time could
///       overwrite data written at the previous end time.
public struct TimeInterval: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The end of the time interval.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The beginning of the time interval.  The default value
  /// for the start time is the end time. The start time must not be
  /// later than the end time.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `TimeInterval`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeInterval().with { $0.endTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.TimeInterval"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
