// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol UptimeCheckServiceStub {
    func listUptimeCheckConfigs(
      request: ListUptimeCheckConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListUptimeCheckConfigsResponse

    func getUptimeCheckConfig(
      request: GetUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.UptimeCheckConfig

    func createUptimeCheckConfig(
      request: CreateUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.UptimeCheckConfig

    func updateUptimeCheckConfig(
      request: UpdateUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.UptimeCheckConfig

    func deleteUptimeCheckConfig(
      request: DeleteUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listUptimeCheckIps(
      request: ListUptimeCheckIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListUptimeCheckIpsResponse
  }

  class UptimeCheckServiceTransport: UptimeCheckServiceStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://monitoring.googleapis.com")
    }

    public func listUptimeCheckConfigs(
      request: ListUptimeCheckConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListUptimeCheckConfigsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/uptimeCheckConfigs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.ListUptimeCheckConfigsResponse.self, from: data)
    }

    public func getUptimeCheckConfig(
      request: GetUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.UptimeCheckConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.UptimeCheckConfig.self, from: data)
    }

    public func createUptimeCheckConfig(
      request: CreateUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.UptimeCheckConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v3/\(pathVariable0)/uptimeCheckConfigs"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.uptimeCheckConfig {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.UptimeCheckConfig.self, from: data)
    }

    public func updateUptimeCheckConfig(
      request: UpdateUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.UptimeCheckConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.uptimeCheckConfig.map({ $0.name }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.uptime_check_config.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.uptimeCheckConfig {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.UptimeCheckConfig.self, from: data)
    }

    public func deleteUptimeCheckConfig(
      request: DeleteUptimeCheckConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v3/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func listUptimeCheckIps(
      request: ListUptimeCheckIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleMonitoringV3.ListUptimeCheckIpsResponse {
      let path = try { () throws -> Swift.String in
        return "/v3/uptimeCheckIps"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleMonitoringV3.ListUptimeCheckIpsResponse.self, from: data)
    }
  }
}
